/** @type {import("tailwindcss").Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b4c9e0",
        "inverse-primary": "#72d9fd",
        "primary-container": "#b7eaff",
        "secondary-fixed-dim": "#d3d4d6",
        "on-secondary-fixed": "#3d4041",
        "surface-bright": "#f7f9fb",
        "inverse-surface": "#0b0f10",
        "on-tertiary-fixed-variant": "#415468",
        "surface-tint": "#006780",
        "on-secondary-container": "#4f5254",
        error: "#9f403d",
        "surface-container-low": "#f0f4f7",
        "inverse-on-surface": "#9a9d9f",
        "secondary-fixed": "#e1e3e4",
        "on-tertiary": "#f7f9ff",
        "on-surface": "#2a3439",
        "on-error-container": "#752121",
        "surface-container-highest": "#d9e4ea",
        "surface-container-high": "#e1e9ee",
        "primary-fixed-dim": "#8be0ff",
        "on-secondary-fixed-variant": "#595c5d",
        "on-primary-fixed-variant": "#00647c",
        "on-background": "#2a3439",
        "secondary-dim": "#515355",
        "primary-dim": "#005a70",
        background: "#f7f9fb",
        primary: "#006780",
        "on-secondary": "#f8f9fb",
        "primary-fixed": "#b7eaff",
        "secondary-container": "#e1e3e4",
        "on-tertiary-container": "#374b5f",
        secondary: "#5d5f61",
        "surface-variant": "#d9e4ea",
        "on-primary-container": "#00596f",
        tertiary: "#4d6175",
        outline: "#717c82",
        surface: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-error": "#fff7f6",
        "surface-dim": "#cfdce3",
        "on-primary-fixed": "#004557",
        "tertiary-container": "#c2d6ef",
        "tertiary-dim": "#415569",
        "error-dim": "#4e0309",
        "outline-variant": "#a9b4b9",
        "on-surface-variant": "#566166",
        "error-container": "#fe8983",
        "on-primary": "#eef9ff",
        "on-tertiary-fixed": "#24384b",
        "tertiary-fixed": "#c2d6ef",
        "surface-container": "#e8eff3",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
